# Configures builds for all branches and deployment on the "master" branch.

language: node_js
node_js: node

install: npm ci
script: npm test && npm run build

deploy:
  provider: firebase
  edge: true
  on:
    branch: master
    # Skip deployment if credentials are unset
    condition: -n $FIREBASE_TOKEN

