# Configures builds for all branches and deployment on the "prod" branch.

language: node_js
node_js: node

install: npm ci
script: npm test && npm run build

deploy:
  provider: pages
  local_dir: build/
  edge: true
  skip-cleanup: true
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN
  on:
    branch: master
